defaults: &defaults
    adapter: mysql2
    encoding: utf8
    reconnect: false
    socket: /tmp/mysql.sock
    pool: 5
    username: root
    password:

development:
    database: parallel_sauce_development
    <<: *defaults

test: &test
    database: parallel_sauce_test
    <<: *defaults

production:
    database: parallel_sauce_production
    <<: *defaults
